# Config file for automatic testing at travis-ci.com
dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.6"
  - "3.8"
  - "3.9"

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install -r requirements.txt

# Command to run tests, e.g. python setup.py test
script: 
  - pytest 
