# ####################################################
# Configuration file for the fish detector

# Parameter values after the semi-columns can be
# modified as needed but section names and indentation
# shoud be kept as is.
# 
# Make sure there is a space between the : and the
# parameter value.
# ####################################################

ENVIRONMENT:
    sound_speed_mps: 1484

TDOA:
    ref_channel: 3
    upsample_res_sec: 0.0000001 #null
    normalize: False

METHOD:
    linearized_inversion: True
    grid_search: False

INVERSION:
    start_model: [-1,-0.5,-0.5] 
    start_model_repeats: 5
    damping_factor: 0.05 #0.2
    stop_delta_m: 0.01
    stop_max_iteration: 200

GRIDSEARCH:
    origin: [0,0,0] 
    spacing_m: 0.1
    radius_m: 3
